name: Release Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    container:
      image: centos/devtoolset-7-toolchain-centos7
    steps:
      - uses: actions/checkout@v2
      - name: dl-choosenim
        run: curl --output init.sh https://nim-lang.org/choosenim/init.sh
      - name: install-nim
        run: sh init.sh -y
      - name: init-nim
        run: echo "::add-path::export PATH=/github/home/.nimble/bin"
      - name: test-nim2
        run: nim -v
      #- name: get-ld-ver-info
      #  run: ld -v
