name: Release Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v2
      - name: dl-nim
        run: curl --output init.sh https://nim-lang.org/choosenim/init.sh
      #- name: init-nim
      #  run: sh init.sh -y
      - name: get-ld-ver-info
        run: ld -v
