name: Release Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: centos:7 #centos/devtoolset-7-toolchain-centos7
    steps:
      - name: Install DevTools
        run: |
          yum install gcc autoconf automake make binutils glibc glibc-devel glibc-static -y
          #yum group install "Development Tools" -y
          #yum install glibc-static libstdc++-static -y
      - uses: actions/checkout@v2
      - name: dl-choosenim
        run: curl --output init.sh https://nim-lang.org/choosenim/init.sh
      - name: install-nim
        run: sh init.sh -y
      - name: init-nim
        run: echo "::add-path::/github/home/.nimble/bin"
      - name: check-versions
        run: |
          nim -v
          ld -v
      - name: build
        run: nim c -o:lin_build -d:danger --panics:on --passL:--static --passC:-std=gnu99 build
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: ./lin_build
          args: --best -q
      - name: See Size
        run: ls -lh lin_build
      - name: Upload Linux Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lin_build
          asset_name: lin_build
          tag: ${{ github.ref }}
