name: Release Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    container:
      image: centos/devtoolset-7-toolchain-centos7
    steps:
      - name: Install DevTools
        run: yum install glibc-static libstdc++-static -y
      - uses: actions/checkout@v2
      - name: dl-choosenim
        run: curl --output init.sh https://nim-lang.org/choosenim/init.sh
      - name: install-nim
        run: sh init.sh -y
      - name: init-nim
        run: echo "::add-path::/github/home/.nimble/bin"
      - name: check-versions
        run: |
          nim -v
          ld -v
      - name: build
        run: nim c -o:mbuild -d:danger --panics:on --passL:--static --passC:--static build
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: ./mbuild
          args: --best -q
      - name: See Size
        run: ls -lh mbuild
